// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs_pevFW3Y6CZVf2DEN_xg6bv8QO0Rn1g',
    appId: '1:642671297822:web:e374085b55b1243941b50f',
    messagingSenderId: '642671297822',
    projectId: 'ecommerce-siku69',
    authDomain: 'ecommerce-siku69.firebaseapp.com',
    storageBucket: 'ecommerce-siku69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5dJQi46Fix4kJVUkK76rvUxvBE90ItX0',
    appId: '1:642671297822:android:41442964613ef8c841b50f',
    messagingSenderId: '642671297822',
    projectId: 'ecommerce-siku69',
    storageBucket: 'ecommerce-siku69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRucuhf6pMNjv3iovGVbVtrVVgHEaE61Q',
    appId: '1:642671297822:ios:ce60165b472411cf41b50f',
    messagingSenderId: '642671297822',
    projectId: 'ecommerce-siku69',
    storageBucket: 'ecommerce-siku69.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRucuhf6pMNjv3iovGVbVtrVVgHEaE61Q',
    appId: '1:642671297822:ios:ce60165b472411cf41b50f',
    messagingSenderId: '642671297822',
    projectId: 'ecommerce-siku69',
    storageBucket: 'ecommerce-siku69.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs_pevFW3Y6CZVf2DEN_xg6bv8QO0Rn1g',
    appId: '1:642671297822:web:c4b707b63ddf68c041b50f',
    messagingSenderId: '642671297822',
    projectId: 'ecommerce-siku69',
    authDomain: 'ecommerce-siku69.firebaseapp.com',
    storageBucket: 'ecommerce-siku69.firebasestorage.app',
  );
}
